### ISSUE TITLE
Way too complicated

### ISSUE THREAD

**Issue by fulldecent** [NetsoftHoldings/public-api-php-demo#4]
Can I please get one or two lines of cURL that achieve the same thing as all this PHP?

**Comment by urkle** [comment]
In the simplest form making a request is simply sending the access token in an `Authorization: Bearer {token}` header.  However you have to have some script code around to consult the expiration of the access token and process refreshing it once a day and saving the updated access/refresh token from that process..

Read our [auth docs on PAT](https://developer.hubstaff.com/authentication#pat)
